version: "3.9"

services:
  vuetify-app:
    container_name: vuetify_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5180:5180"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
